import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/shared/Navbar'
import { NextUIProviders } from '@/lib/NextUIProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#141412]'>
        <NextUIProviders>
        <Navbar/>
        {children}
        </NextUIProviders>
      </body>
    </html>
  )
}
